### ISSUE TITLE
state feedback value of null

### ISSUE THREAD

**Issue by smartboart** [gysmo38/mitsubishi2MQTT#111]
Hello, after update to latest version, i have now this feedback while heating see string below...
mode null and action null, which should show heat and heating..

{"roomTemperature":23.5,"temperature":25,"fan":"1","vane":"1","wideVane":"|","mode":null,"action":null,"compressorFrequency":0}

should look like this...
{"roomTemperature":22.5,"temperature":25,"fan":"1","vane":"1","action":"heating","mode":"heat"}

so there is some mistake happening, while adding the compressorFrequency...

**Comment by melyux** [comment]
I was getting this issue when testing the code (it seemed the mode and action would randomly both start showing `null` in the MQTT state out of nowhere and stay that way until the mode/power was changed), but I thought I fixed it by making sure the `hpGetMode` and `hpGetAction` functions were returning Strings, though there's still a `.c_str()` value that was there before. I haven't had the problem since then, but this looks like it's still happening.

Maybe someone more versed in C and Arduino strings can take a look at those methods and see if I did something wrong. Maybe heap fragmentation (should we switch to Flash strings?), or something more obvious? Like why are we using a `c_str()` when the function's supposed to be returning a normal String? @gysmo38 @mamrai1 

https://github.com/gysmo38/mitsubishi2MQTT/blob/ea41c974f3277d816974d08fafb5bb9ecc183178/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1261-L1289

**Comment by melyux** [comment]
I've put in PR #112 that stops converting the String into a C string, but I'm not sure if that'll be enough to fix this since I can't reproduce it anymore. @smartboart

**Comment by smartboart** [comment]
Hello melyux, 
thanks for your  support.
i have implemented your changes into the projekt on my pc and created a bin file to load the new firmware. I will test if it will help and let you know..

**Comment by smartboart** [comment]
Ok, the feedback now is much better. But there is still another problem with the fan mode which worked before...
the mqtt mode feedback and mqqt control for fan only (idle )   with mode = FAN is not working.
I have 2 units so it is easy for me to compare...
The fan mode cannot be switched on over mqtt while writing the mode with FAN..nothing happens....If i switch on the fan mode via the web gui it is going to fan mode, but the mqtt feedback in this case is: {"roomTemperature":20.5,"temperature":24,"fan":"1","vane":"3","wideVane":"|","action":"off","mode":"off"}

and should look like this:
{"roomTemperature":20.5,"temperature":24,"fan":"1","vane":"3","wideVane":"|","action":"idle","mode":"fan_only"}

**Comment by brackw** [comment]
The issue persists with hpGetMode (and similarly hpGetAction) returning null after a ~6 times of being called.

I used mqtt debug to publish rootInfo["mode"] from within hpStatusChanged to see it correctly output 'heat' after reboot before becoming null, but a separate debug statement within hpGetMode function would still publish 'heat'.

It probably has something to do with arduino strings, but I am more hardware than software so if there is something inherently wrong here I am not seeing it.

**Comment by melyux** [comment]
@smartboart So you’re saying setting the mode to fan over MQTT `mode/set` is not actually, physically turning the fan on? Or is it just not reporting that it’s on?

@brackw Is that with my PR? I don’t see anything obviously wrong either. I’m not getting the null thing when in cooling/drying mode, strangely, and mine doesn’t support heating in the first place, so I can’t reproduce it. There’s something wrong happening with the strings (or maybe ArduinoJson’s JSON document size allocation?), but I haven’t been able to figure it out either

**Comment by smartboart** [comment]
Yes it is not turning physically the fan on over mqtt... And if I turn it on over web gui it is physically on,but it is not reporting it is on over mqtt eather.. .

**Comment by smartboart** [comment]
If you want I can upload the project or the bin file I am using without any trouble to compare.. I am using the code from August this year and just changed the things regarding the wifi reconnect and left the other changees away....

**Comment by brackw** [comment]
@melyux Yes, this was with your PR code implemented into my local copy.

On a hunch I added:

rootInfo.clear();

Just before new settings are written into rootInfo.

I'm pretty sure this is not the right way to fix issues with buffer issues (if thats even what is happening), but I flashed this change to 4 heatpumps, one is running in cool and one is set to heat (but not running due to current cool request) and all units have not returned null yet.

I may be just masking the issue rather than fixing it.

Unfortunately I cannot replicate the issue @smartboart is having. I can set to fan from mqtt/HA without issue.

**Comment by smartboart** [comment]
OK.. If nobody else have this issue, do not waste your time with that. .. I have a solution for me which is working fine... . Thanks for your support in this matter.. .

**Comment by lesleypersyn** [comment]
I just tested the latest from 'master' and still have the same 'null' issue.
'{"roomTemperature":25.5,"temperature":18,"fan":"AUTO","vane":"SWING","wideVane":"SWING","mode":null,"action":null,"compressorFrequency":0}' 
Did i use the wrong version?

**Comment by brackw** [comment]
@lesleypersyn If you want to try adding rootInfo.clear(); at line 1296 within hpStatusChanged(heatpumpStatus currentStatus) to clear the JsonDocument before filling it with new status info to see if it appears to resolve it for you as well. 

I wouldn't say this is the fix since I don't know the exact root cause and why @melyux isn't seeing it occur. Or if it causes any unforeseen issues.

**Comment by lesleypersyn** [comment]
@brackw Add rootInfo.clear(); at line 1296 with latest master, compiled, uploaded.
previous result: {"roomTemperature":21.5,"temperature":18,"fan":"AUTO","vane":"SWING","wideVane":"SWING","mode":null,"action":null,"compressorFrequency":0}
new result:
{"roomTemperature":21.5,"temperature":18,"fan":"AUTO","vane":"SWING","wideVane":"SWING","mode":"off","action":"off","compressorFrequency":0}

This solves the "null" string issue.
I hope this helps the further development.

**Comment by Stendec1** [comment]
@brackw Add rootInfo.clear(); at line 1296 with latest master, compiled, uploaded.
Did work for me too.

Additionally and surprisingly it also fixed #87 for me.

**Comment by Stendec1** [comment]
@brackw, @lesleypersyn In the description of Version 6 / API JsonDocument I read the following:

_"I strongly recommend against using a global JsonDocument because you would be troubled by the monotonic allocator, and would make inefficient use of your RAM.
On the contrary, I recommend declaring a short-lived JsonDocument that you use only in your serialization functions."_

Looks like it is defined globally at line 80:
//Local state
StaticJsonDocument<JSON_OBJECT_SIZE(12)> rootInfo;

Using rootInfo.clear() might be a good alternative to declaring a short-lived JsonDocument I guess.

**Comment by lesleypersyn** [comment]
@Stendec1 correct, I'm checking this also in depth.
There seems multiple issue's with this topic. I'm working on this...
If you use serializeJson after filling in the data the rootInfo is cleared automatically. But in this case it isn't.
Why it's defined here again with other memory pool sizes is not clear for me. The rootInfo is expanded from the first editions and not adjusted correctly... (i think) See below:
https://github.com/gysmo38/mitsubishi2MQTT/blob/b0eabf4f2f370e33366f01ee73569f04d86ab500/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1223-L1224
JSON_OBJECT_SIZE should be 8 when verifying with [https://arduinojson.org/v6/assistant/](url) The 6 above generates probably a problem!

I'll do some more testing/optimizing...
edit: changing/removing 1223-1224 this is not a solution.
state-> {"roomTemperature":20,"temperature":20,"fan":"AUTO","vane":"SWING","wideVane":"SWING","mode":null,"action":null}

**Comment by Stendec1** [comment]
@lesleypersyn I think I know why it is defined there with another memory pool size. If you don't you get following result: 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/842090/98109649-2d621200-1e9e-11eb-90ec-eb03f065b4a2.png">

where it should be:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/842090/98110349-3bfcf900-1e9f-11eb-9f90-15dee4467217.png">

**Comment by mamrai1** [comment]
Sorry I haven't had time to check... For sure the problem lies on latest optimizations from @melyux..... I have to update my code and see.. Maybe somewhere settings and state get mixed?

**Comment by lesleypersyn** [comment]
Spend too much time on this. Replaced many parts but same issue.
Found this one: [https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/](https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/)
The cause is due the change of @melyux to change the location of StaticJsonDocument (to global/local). This is needed due functionality. So solution 2 is the correct solution to handle the function.

Adding rootInfo.clear(); between https://github.com/gysmo38/mitsubishi2MQTT/blob/b0eabf4f2f370e33366f01ee73569f04d86ab500/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1295-L1297 like @brackw told is a valid solution. ok?

**Comment by mamrai1** [comment]
> Spend too much time on this. Replaced many parts but same issue.
> Found this one: [https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/](url)
> The cause is due the change of @melyux to change the location of StaticJsonDocument (to global/local). This is needed due functionality. So solution 2 is the correct solution to handle the function.
> 
> Adding rootInfo.clear(); between
> 
> https://github.com/gysmo38/mitsubishi2MQTT/blob/b0eabf4f2f370e33366f01ee73569f04d86ab500/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1295-L1297
> 
> like @brackw told is a valid solution. ok?

Pull request and call it a day?

**Comment by mamrai1** [comment]
after playing around it seems the solution is not working...at least for me...it throws null values after a couple of hours.

**Comment by mamrai1** [comment]
@lesleypersyn Do you use latest swicago library?

**Comment by mamrai1** [comment]
@melyux  can you please check your heatpump library you use with latest changes? 
there is a change on latest version of swicago library regarding externalupdates and autoupdate that cause problems

**Comment by lesleypersyn** [comment]
@mamrai1, i've seen some questions. In my case i use Heatpump v 1.0.0 (see platformio.ini)

**Comment by melyux** [comment]
@mamrai1 I've been using the HeatPump library from April 29, 2020. I haven't updated it to include the 7 commits since then. It'd be weird if that were causing this problem cuz I had this problem before too until expanding the JsonDocument size during dev.

@Stendec1 Good catch, I was using this simply to store the local state but didn't know about that catch.

An alternative solution could be to store the local state in a different way, and transfer the information to an ad hoc JsonDocument whenever we need to serialize, like the documentation suggests. I had found a global JsonDocument to be the simplest and most efficient way to keep state, but obviously it's causing some unforeseen problems.

**Comment by lesleypersyn** [comment]
@melyux Checked [https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/](https://arduinojson.org/v6/faq/i-found-a-memory-leak-in-the-library/) already? It's a solution. (solution 2) Not a memory leak.

**Comment by Stendec1** [comment]
@lesleypersyn, @melyux, @mamrai1, 
Looks like rootInfo.clear() is the easiest way to go. I had no issues since adding it 20 days ago.

**Comment by smartboart** [comment]
Mee too...

**Comment by lesleypersyn** [comment]
Can someone check what went wrong with this topic? I published a time ago a PR. The changes seems like they are done but the PR is still open (and now in conflict)
If i check git blame then i can see it's changed due the PR #118 strange? or not? see below;
[https://github.com/gysmo38/mitsubishi2MQTT/blob/7875966340c839cbc110fc1372930e7eb0000caa/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1223](https://github.com/gysmo38/mitsubishi2MQTT/blob/7875966340c839cbc110fc1372930e7eb0000caa/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1223)

[https://github.com/gysmo38/mitsubishi2MQTT/blame/7875966340c839cbc110fc1372930e7eb0000caa/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1223](https://github.com/gysmo38/mitsubishi2MQTT/blame/7875966340c839cbc110fc1372930e7eb0000caa/src/mitsubishi2mqtt/mitsubishi2mqtt.ino#L1223)
Thanks for checking.

**Comment by melyux** [comment]
From a cursory look, it looks like @wabarkley applied your PR changes on top of his own branch for his own (unrelated) PR #119, which was merged. So I think your changes are in through him now.

**Comment by wabarkley** [comment]
> From a cursory look, it looks like @wabarkley applied your PR changes on top of his own branch for his own (unrelated) PR #119, which was merged. So I think your changes are in through him now.

Yeah, one of these days I'll figure out how to do proper configuration management.

**Comment by lesleypersyn** [comment]
> > From a cursory look, it looks like @wabarkley applied your PR changes on top of his own branch for his own (unrelated) PR #119, which was merged. So I think your changes are in through him now.
> 
> Yeah, one of these days I'll figure out how to do proper configuration management.

Complex and intuitive ... (still learning every day...)

**Comment by gysmo38** [comment]
old issue. Open a new one if still have the issue
